Bu yerda

In [2]:
import numpy as np
import pandas as pd

In [3]:
!git clone https://github.com/Xusanman/praktikum_datasets

Cloning into 'praktikum_datasets'...
remote: Enumerating objects: 45, done.
remote: Counting objects: 100% (45/45), done.
remote: Compressing objects: 100% (43/43), done.
remote: Total 45 (delta 1), reused 0 (delta 0), pack-reused 0 (from 0)
Receiving objects: 100% (45/45), 7.17 MiB | 7.58 MiB/s, done.
Resolving deltas: 100% (1/1), done.

In [4]:
df = pd.read_csv("praktikum_datasets/uzbekistan.csv")
df.head(5)

          Boʻlinishi  Maydoni (kv.km)    Aholisi
0   Andijon viloyati           4200.0  1899000.0
1    Buxoro viloyati          39400.0  1384700.0
2  Fargʻona viloyati           6800.0  2597000.0
3    Jizzax viloyati          20500.0   910500.0
4    Xorazm viloyati           6300.0  1200000.0

In [5]:
pd.read_excel('praktikum_datasets/uzbekistan.xlsx', index_col=0, names=['hudud', 'maydon', 'aholi'])

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000

In [6]:
pd.read_csv("praktikum_datasets/automobile_data.csv", sep=",", index_col='index', nrows=15)

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450
5,audi,sedan,99.8,177.3,ohc,five,110,19,15250
6,audi,wagon,105.8,192.7,ohc,five,110,19,18920
9,bmw,sedan,101.2,176.8,ohc,four,101,23,16430
10,bmw,sedan,101.2,176.8,ohc,four,101,23,16925
11,bmw,sedan,101.2,176.8,ohc,six,121,21,20970
13,bmw,sedan,103.5,189.0,ohc,six,182,16,30760
14,bmw,sedan,103.5,193.8,ohc,six,182,16,41315
15,bmw,sedan,110.0,197.0,ohc,six,182,15,36880
16,chevrolet,hatchback,88.4,141.1,l,three,48,47,5151
17,chevrolet,hatchback,94.5,155.9,ohc,four,70,38,6295

#Faylga yozish

In [7]:
df = pd.read_excel('praktikum_datasets/uzbekistan.xlsx', index_col=0, names=['hudud', 'maydon', 'aholi'])
df

                               maydon    aholi
hudud
Andijon viloyati                 4200  1899000
Buxoro viloyati                 39400  1384700
Fargʻona viloyati                6800  2597000
Jizzax viloyati                 20500   910500
Xorazm viloyati                  6300  1200000
Namangan viloyati                7900  1862000
Navoiy viloyati                110800   767500
Qashqadaryo viloyati            28400  2029000
Qoraqalpogʻiston Respublikasi  160000  1200000
Samarqand viloyati              16400  2322000
Sirdaryo viloyati                5100   648100
Surxondaryo viloyati            20800  1676000
Toshkent viloyati               15300  4450000

In [12]:
df.to_excel("newuzb.xlsx")

In [9]:
obj = df.maydon
obj

hudud
Andijon viloyati                   4200
Buxoro viloyati                   39400
Fargʻona viloyati                  6800
Jizzax viloyati                   20500
Xorazm viloyati                    6300
Namangan viloyati                  7900
Navoiy viloyati                  110800
Qashqadaryo viloyati              28400
Qoraqalpogʻiston Respublikasi    160000
Samarqand viloyati                16400
Sirdaryo viloyati                  5100
Surxondaryo viloyati              20800
Toshkent viloyati                 15300
Name: maydon, dtype: int64

In [26]:
obj.to_csv("uzmaydon.csv")

In [33]:
series = pd.read_csv("uzmaydon.csv", index_col='hudud').squeeze("columns")
series

hudud
Andijon viloyati                   4200
Buxoro viloyati                   39400
Fargʻona viloyati                  6800
Jizzax viloyati                   20500
Xorazm viloyati                    6300
Namangan viloyati                  7900
Navoiy viloyati                  110800
Qashqadaryo viloyati              28400
Qoraqalpogʻiston Respublikasi    160000
Samarqand viloyati                16400
Sirdaryo viloyati                  5100
Surxondaryo viloyati              20800
Toshkent viloyati                 15300
Name: maydon, dtype: int64

In [34]:
series.to_excel("series_excel.xlsx")

In [38]:
df2 = pd.read_csv("praktikum_datasets/automobile_data.csv", sep=",", index_col='index')
df2

,company,body-style,wheel-base,length,engine-type,num-of-cylinders,horsepower,average-mileage,price
index,,,,,,,,,
0,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,13495.0
1,alfa-romero,convertible,88.6,168.8,dohc,four,111,21,16500.0
2,alfa-romero,hatchback,94.5,171.2,ohcv,six,154,19,16500.0
3,audi,sedan,99.8,176.6,ohc,four,102,24,13950.0
4,audi,sedan,99.4,176.6,ohc,five,115,18,17450.0
...,...,...,...,...,...,...,...,...,...
81,volkswagen,sedan,97.3,171.7,ohc,four,85,27,7975.0
82,volkswagen,sedan,97.3,171.7,ohc,four,52,37,7995.0
86,volkswagen,sedan,97.3,171.7,ohc,four,100,26,9995.0
87,volvo,sedan,104.3,188.8,ohc,four,114,23,12940.0
88,volvo,wagon,104.3,188.8,ohc,four,114,23,13415.0

In [44]:
df2.to_excel("sample_data/car_data.xlsx", index=False, columns=['company', 'body-style', 'price'])